In [1]:
import json
import os

import matplotlib.pyplot as plt
import netCDF4 as nc
import numpy as np
import seaborn as sns
import xarray as xr

In [2]:
filedir = '/glade/work/abaker/jian/puma-cam6/'
pydir = '/glade/u/home/abaker/repos/PyCECT/'

In [3]:
save_filename = filedir + 'savefile_3runs.nc'
ds = xr.open_dataset(save_filename)
sum_filename = filedir + 'uf.ens.f19_f19_mg17.F2000dev.pumas.summary_c090823.nc'
sum_ds = xr.open_dataset(sum_filename)

In [4]:
# from savefile
test_size = ds.dims['test_size']
ens_size = ds.dims['ens_size']
nvars = ds.dims['nvars']

# get var names
vars = ds['vars'].values

# get test scores and means
t_scores = ds['scores'].values
t_std_gm = ds['std_gm'].values
t_gm = ds['gm'].values

# get ens pc scores distribution (nvars = npcs)
# these are mean zero, so array just contains sigma)
ens_score_dist = ds['ens_sigma_scores'].values
# this is the  standardized global means (nvars by ens_size) => so dist mean = 0 for each var
ens_std_gm = ds['ens_std_gm'].values

In [5]:
# from sumfile
ens_gm = sum_ds['global_mean'].values
P = sum_ds['loadings_gm'].values

In [6]:
str_vars = []
for i in range(vars.size):
    str_vars.append(vars[i].decode('UTF-8'))

In [7]:
name = 'dst_a2'
var_id = str_vars.index(name)
var_id

98

In [8]:
print('Ensemble standardized global mean distribution')
print('99.5 percentile = ', np.percentile(ens_std_gm[var_id, :], 99.5))
print('mean = ', ens_std_gm[var_id, :].mean())
print('min = ', ens_std_gm[var_id, :].min())
print('max = ', ens_std_gm[var_id, :].max())

Ensemble standardized global mean distribution
99.5 percentile =  1.994886847102695
mean =  -4.056691490664629e-14
min =  -4.507574812044302
max =  2.4474573240987207


In [9]:
print('Test standardized gm')
t_std_gm[var_id, :]

Test standardized gm


array([  1.1576871 , -25.00288693, -25.07065588])

In [10]:
print('Ensemble ORIG global mean distribution')
print('mean = ', ens_gm[var_id, :].mean())
print('min = ', ens_gm[var_id, :].min())
print('max = ', ens_gm[var_id, :].max())

Ensemble ORIG global mean distribution
mean =  6.178443962526598e-15
min =  6.11234271347235e-15
max =  6.214334656053772e-15


In [11]:
print('Test ORIG gm')
t_gm[var_id, :]

Test ORIG gm


array([6.19542084e-15, 5.81178958e-15, 5.81079578e-15])

In [12]:
# remember 0-index here compared to the pyCECT output
# PC 5: failed 2 runs  [2, 3]
# PC 6: failed 3 runs  [1, 2, 3]
# PC 7: failed 2 runs  [2, 3]
# PC 8: failed 2 runs  [2, 3]

pc_id = 4  # same as 5 above

In [13]:
print('ensemble: sigma = ', ens_score_dist[pc_id])
print('ensemble: 2*sigma = ', 2 * ens_score_dist[pc_id])

ensemble: sigma =  2.9578030763011744
ensemble: 2*sigma =  5.915606152602349


In [14]:
t_scores[pc_id, :]

array([-1.07940943, 24.39905882, 27.25332384])

In [15]:
# which variables contribute most to this pc?
# each column of P corresponds to the variable weights of each PC, so PC1 weights are in the first column (remember 0-indexing)
P.shape
wts = abs(P[:, pc_id])
sort_wts = np.argsort(wts)[::-1]

In [16]:
# look at the 20 biggest weights
sort_wts[:20]

array([215, 209, 212,  99, 240, 213, 238,  98, 210, 207, 102, 111,  97,
       218, 217, 178, 264, 263, 177, 274])

In [17]:
wts[sort_wts][:20]

array([0.26960287, 0.26810269, 0.26627399, 0.23106317, 0.22440001,
       0.20459294, 0.20453547, 0.19505496, 0.19475654, 0.18880373,
       0.17643708, 0.13342117, 0.12903841, 0.11046072, 0.10163009,
       0.09753223, 0.09752476, 0.09752093, 0.09750298, 0.0891191 ])

In [18]:
# which vars are these?
for i in sort_wts[:20]:
    print(str_vars[i], ": ", wts[i])

dst_a3_SRF :  0.2696028695522857
dst_a1_SRF :  0.2681026914133036
dst_a2_SRF :  0.2662739908701279
dst_a3 :  0.23106317443207447
num_a3_SRF :  0.22440001202523988
dst_a3DDF :  0.2045929363567556
num_a3DDF :  0.2045354707161037
dst_a2 :  0.19505495851615695
dst_a2DDF :  0.194756539971718
dst_a1DDF :  0.18880372643904972
dst_c3 :  0.17643707717616158
num_a3 :  0.13342117237349407
dst_a1 :  0.1290384126146087
dst_c3SFWET :  0.11046071705935837
dst_c2SFWET :  0.10163008633074497
SO2_CMXF :  0.09753223394296479
so4_a2_CMXF :  0.09752476462307504
so4_a2_CLXF :  0.09752093359392637
SO2_CLXF :  0.09750297514458574
soa_a1_SRF :  0.08911909539703942


In [19]:
if 'T' in str_vars:
    print('yes')

yes


In [20]:
i = "T"
str_vars.index(i)

64

In [21]:
li = ['bob', 'joe', 'frank', 'Q']
indx = [1, 2]

In [22]:
jdict = {}

In [23]:
jdict["Hey"] = li

In [24]:
jdict

{'Hey': ['bob', 'joe', 'frank', 'Q']}

In [25]:
with open("sample.json", "w") as outfile:
    json.dump(jdict, outfile)

In [34]:
li.remove('joe')

In [35]:
li

['bob', 'frank', 'Q']

In [36]:
len(li)

3

In [8]:
first_file = nc.Dataset('uf_test.nc', 'r')

In [4]:
mpas_file = nc.Dataset('history_full.000.nc', 'r')

In [5]:
vars_dict = mpas_file.variables

In [6]:
vars_dict.keys()

dict_keys(['qv', 'qc', 'qr', 'qi', 'qs', 'qg', 'latCell', 'lonCell', 'xCell', 'yCell', 'zCell', 'indexToCellID', 'latEdge', 'lonEdge', 'xEdge', 'yEdge', 'zEdge', 'indexToEdgeID', 'latVertex', 'lonVertex', 'xVertex', 'yVertex', 'zVertex', 'indexToVertexID', 'cellsOnEdge', 'nEdgesOnCell', 'nEdgesOnEdge', 'edgesOnCell', 'edgesOnEdge', 'weightsOnEdge', 'dvEdge', 'dcEdge', 'angleEdge', 'areaCell', 'areaTriangle', 'cellsOnCell', 'verticesOnCell', 'verticesOnEdge', 'edgesOnVertex', 'cellsOnVertex', 'kiteAreasOnVertex', 'meshDensity', 'zgrid', 'fzm', 'fzp', 'zz', 'initial_time', 'xtime', 'u', 'w', 'pressure', 'surface_pressure', 'rho', 'theta', 'relhum', 'divergence', 'vorticity', 'ke', 'uReconstructZonal', 'uReconstructMeridional', 'ertel_pv', 'u_pv', 'v_pv', 'theta_pv', 'vort_pv', 'depv_dt_lw', 'depv_dt_sw', 'depv_dt_bl', 'depv_dt_cu', 'depv_dt_mix', 'dtheta_dt_mp', 'depv_dt_mp', 'depv_dt_diab', 'depv_dt_fric', 'depv_dt_diab_pv', 'depv_dt_fric_pv', 'iLev_DT', 'i_rainnc', 'rainnc', 'precipw',

In [19]:
for k, v in vars_dict.items():
    dd = vars_dict[k][:].dtype
    print(dd)
    if dd == 'int32':
        print('yup')

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
int32
yup
float64
float64
float64
float64
float64
int32
yup
float64
float64
float64
float64
float64
int32
yup
int32
yup
int32
yup
int32
yup
int32
yup
int32
yup
float64
float64
float64
float64
float64
float64
int32
yup
int32
yup
int32
yup
int32
yup
int32
yup
float64
float64
float64
float64
float64
float64
|S1
|S1
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
int32
yup
int32
yup
float64
float64
float64
int32
yup
float64
int32
yup
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
|S1
int32
yup
int32
yup
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


In [9]:
lev_data = first_file.variables["lev"]

In [10]:
var = vars_dict["iLev_DT"]

In [11]:
var[:].dtype

dtype('int32')

In [12]:
type(var)

netCDF4._netCDF4.Variable

In [31]:
b

masked_array(data=[  3.64346569,   7.59481965,  14.35663225,  24.61222   ,
                    35.92325002,  43.19375008,  51.67749897,  61.52049825,
                    73.75095785,  87.82123029, 103.31712663, 121.54724076,
                   142.99403876, 168.22507977, 197.9080867 , 232.82861896,
                   273.91081676, 322.24190235, 379.10090387, 445.9925741 ,
                   524.68717471, 609.77869481, 691.38943031, 763.40448111,
                   820.85836865, 859.53476653, 887.02024892, 912.64454694,
                   936.19839847, 957.48547954, 976.32540739, 992.55609512],
             mask=False,
       fill_value=1e+20)

In [32]:
first_file.close()

In [35]:
b[:]

masked_array(data=[  3.64346569,   7.59481965,  14.35663225,  24.61222   ,
                    35.92325002,  43.19375008,  51.67749897,  61.52049825,
                    73.75095785,  87.82123029, 103.31712663, 121.54724076,
                   142.99403876, 168.22507977, 197.9080867 , 232.82861896,
                   273.91081676, 322.24190235, 379.10090387, 445.9925741 ,
                   524.68717471, 609.77869481, 691.38943031, 763.40448111,
                   820.85836865, 859.53476653, 887.02024892, 912.64454694,
                   936.19839847, 957.48547954, 976.32540739, 992.55609512],
             mask=False,
       fill_value=1e+20)

In [ ]:
nc_sumfile = nc.Dataset('testsum.nc', 'w', format='NETCDF4_CLASSIC')
nlev = 30
nc_sumfile.createDimension('nlev', nlev)
v_lev = nc_sumfile.createVariable('lev', 'f8', ('nlev',))

In [ ]:
v_lev[:] = lev_data_copy[:]